2025-05-26 20:09:19,194 INFO    MainThread:3270437 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-05-26 20:09:19,194 INFO    MainThread:3270437 [wandb_setup.py:_flush():70] Configure stats pid to 3270437
2025-05-26 20:09:19,194 INFO    MainThread:3270437 [wandb_setup.py:_flush():70] Loading settings from /home/shchoi/.config/wandb/settings
2025-05-26 20:09:19,194 INFO    MainThread:3270437 [wandb_setup.py:_flush():70] Loading settings from /home/shchoi/workspace/DSVT/tools/wandb/settings
2025-05-26 20:09:19,195 INFO    MainThread:3270437 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-05-26 20:09:19,195 INFO    MainThread:3270437 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/shchoi/workspace/DSVT/tools/wandb/run-20250526_200919-suzadlu4/logs/debug.log
2025-05-26 20:09:19,195 INFO    MainThread:3270437 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/shchoi/workspace/DSVT/tools/wandb/run-20250526_200919-suzadlu4/logs/debug-internal.log
2025-05-26 20:09:19,497 WARNING MainThread:3270437 [wandb_init.py:init():1681] [no run ID] interrupted
Traceback (most recent call last):
  File "/home/shchoi/anaconda3/envs/open3d_data/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1671, in init
    _monkeypatch_tensorboard()
  File "/home/shchoi/anaconda3/envs/open3d_data/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1272, in _monkeypatch_tensorboard
    tb_module.patch()
  File "/home/shchoi/anaconda3/envs/open3d_data/lib/python3.10/site-packages/wandb/integration/tensorboard/monkeypatch.py", line 43, in patch
    c_writer = wandb.util.get_module(TENSORBOARD_C_MODULE, lazy=False)
  File "/home/shchoi/anaconda3/envs/open3d_data/lib/python3.10/site-packages/wandb/util.py", line 254, in get_module
    return import_module(name)
  File "/home/shchoi/anaconda3/envs/open3d_data/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/shchoi/.local/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/shchoi/.local/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/shchoi/.local/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
KeyboardInterrupt
2025-05-26 20:09:19,584 INFO    MsgRouterThr:3270437 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
